# Generated by Snap version: 1.0

class Dog:
	def __init__(self, age, breed, id, name):
		self.age = age
		self.breed = breed
		self.id = id
		self.name = name

class dog:
	def __init__(self):
		pass

	def listDogs(self, ):
		"""
		Returns a list of dogs in the system.
		"""
		return self.dogsapp_receiver.list_dogs()

	def getDog(self, id):
		"""
		Returns detailed information about a dog with the given ID.
		"""
		return self.dogsapp_receiver.get_dog(id)
