// Generated by Snap version: 1.0
package dogsappsdk

// Returns detailed information about a dog with the given ID.
func (o *Dog) GetDog(id int) (Dog, error) {
	return o.DogsAppReceiver.GetDog(id)
}

// Returns a list of dogs in the system.
func (o *Dog) ListDogs() () {
	return o.DogsAppReceiver.ListDogs()
}

