// Generated by Snap version: 1.0
class Dog {
	constructor(data) {
		this.id = data.id;
		this.name = data.name;
		this.breed = data.breed;
		this.age = data.age;
	}
}
module.exports.Dog = Dog;

class dog {
	// Returns a list of dogs in the system.
	listDogs() {
		return this.dogsAppReceiver.listDogs();
	}
	// Returns detailed information about a dog with the given ID.
	getDog(id) {
		return this.dogsAppReceiver.getDog(id);
	}
}
module.exports.dog = dog;
