// Generated by Snap version: 1.0

#[allow(dead_code)]
pub mod dogsappsdk {
	#[derive(Debug)]
	pub struct Dog {
		pub age: i32,
		pub id: i32,
		pub name: String,
		pub breed: String,
	}

	/// Returns a list of dogs in the system.
	pub fn listdogs(&self, ) -> Result<Vec<Dog>, Error> {
		self.dogsapp_receiver::list_dogs()
	}

	/// Returns detailed information about a dog with the given ID.
	pub fn getdog(&self, id: i32) -> Result<Dog, Error> {
		self.dogsapp_receiver::get_dog(id: i32)
	}

}
